replicaCount: 1

image:
  repository: kylib4444
  tag: "v1.0.0-879bcc9"
  arch: amd64

secret:
  name: kbot
  tokenKey: token
  tokenName: TELE_TOKEN

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: false
  name: ""