name: KBOT-CICD

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} 

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Debug Variables
        run: echo "Registry is ${{ env.REGISTRY }} and Owner is ${{ github.repository_owner }}"
        
      - name: Run test
        run: make test

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        run: |
          make image push \
            REGISTRY=ghcr.io \
            USERNAME=${{ github.repository_owner }} \
            TARGETOS=linux \
            TARGETARCH=amd64